name: Auto Deploy to cPanel via FTP

on:
  push:
    branches:
      - main

# Prevents multiple pushes from running at the same time and slowing down FTP transfers
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-deploy:
    name: Deploy Theme Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Required for the FTP action to perform delta comparisons

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: wp-content/themes/thegem-child/
          exclude: |
            **/.git**
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**